-- 创建HSCMP数据文件目录
-- ALTER DISKGROUP DATA ADD DIRECTORY '+DATA/CLUSTERDB/DATAFILE/HSCMP'

-- 初始化参数
-- spfile='D:\APP\ADMINISTRATOR\PRODUCT\11.2.0\DBHOME_1\DATABASE\SPFILEHSCMB.ORA'
-- ALTER SYSTEM SET db_recovery_file_dest_size = 42949672960 SCOPE=BOTH

-- SHUTDOWN immediate
-- STARTUP mount
-- ALTER DATABASE ARCHIVELOG
-- ALTER DATABASE FLASHBACK ON
-- ALTER DATABASE OPEN READ WRITE
-- 该启动命令将使用一个临时文件作为 pfile (其中包含以下 init.ora 参数):
-- spfile='D:\APP\ADMINISTRATOR\PRODUCT\11.2.0\DBHOME_1\DATABASE\SPFILEHSCMB.ORA'

-- 建立HSCMP表空间
-- 空间大小参考CMP数据取值（2010-09-22）
-- 1034.47253418 seconds
CREATE SMALLFILE TABLESPACE "HSCMP_TBL" DATAFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_TBL' SIZE 10G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- 317.23602295 seconds
CREATE SMALLFILE TABLESPACE "HSCMP_IDX" DATAFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_IDX' SIZE 6G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- 26.11306381 seconds
CREATE SMALLFILE TABLESPACE "HSCMP_TBL_LOG" DATAFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_TBL_LOG' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- 202.17424011 seconds
CREATE SMALLFILE TABLESPACE "HSCMP_TBL_STK" DATAFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_TBL_STK' SIZE 4G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- 1089.2857666 seconds
CREATE SMALLFILE TABLESPACE "HSCMP_TBL_SAL" DATAFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_TBL_SAL' SIZE 20G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
-- 8.41255188 seconds
CREATE SMALLFILE TEMPORARY TABLESPACE "HSCMP_TEMP" TEMPFILE 'E:\HSCMB_DATA\HSCMB\data\HSCMP_TEMP' SIZE 100M AUTOEXTEND ON NEXT 100K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

-- 海信方面指出，此表空间及其用户非必需 
-- CREATE TABLESPACE "HSCMP_COM" DATAFILE '+DATA(DATAFILE)/CLUSTERDB/DATAFILE/HSCMP/HSCMP_COM' SIZE 1G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- 建立HSCMP用户

CREATE USER "HSCMP" PROFILE "DEFAULT" IDENTIFIED BY "hscmp" DEFAULT TABLESPACE "HSCMP_TBL" TEMPORARY TABLESPACE "HSCMP_TEMP" ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "HSCMP" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "HSCMP" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "HSCMP" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT "CONNECT" TO "HSCMP" WITH ADMIN OPTION;
GRANT "DBA" TO "HSCMP" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "HSCMP";

-- 建立readhscmp用户

CREATE USER "READHSCMP" PROFILE "DEFAULT" IDENTIFIED BY "readhscmp" DEFAULT TABLESPACE "HSCMP_TBL" TEMPORARY TABLESPACE "HSCMP_TEMP" ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "READHSCMP" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "READHSCMP" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "READHSCMP" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT "CONNECT" TO "READHSCMP" WITH ADMIN OPTION;
GRANT "DBA" TO "READHSCMP" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "READHSCMP";


-- 建立hscmp_com用户
-- 海信方面指出，此用户及其表空间非必需

-- CREATE USER "HSCMP_COM" PROFILE "DEFAULT" IDENTIFIED BY "hscmp_com" DEFAULT TABLESPACE "HSCMP_COM" TEMPORARY TABLESPACE "HSCMP_TEMP" ACCOUNT UNLOCK;


-- 建立readhscmp用户后，需要执行hscmp的存储过程sSys_Create_Synonym来定义同义词（此存储过程需要在导入CMP数据库后执行）。
-- 未导入数据库文件时此过程并不存在。

-- select * from dba_types where type_oid like 'FD5F%'




