-- 建立hscmp表空间

CREATE SMALLFILE TABLESPACE "HSCMP_TBL" DATAFILE 'D:\ORADATA\hscmp\HSCMP_TBL' SIZE 20G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HSCMP_IDX" DATAFILE 'D:\ORADATA\HSCMP\HSCMP_IDX' SIZE 10G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HSCMP_TBL_LOG" DATAFILE 'D:\ORADATA\HSCMP\HSCMP_TBL_LOG' SIZE 3G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HSCMP_TBL_STK" DATAFILE 'D:\ORADATA\HSCMP\HSCMP_TBL_STK' SIZE 5G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HSCMP_TBL_SAL" DATAFILE 'D:\ORADATA\HSCMP\HSCMP_TBL_SAL' SIZE 15G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TEMPORARY TABLESPACE "HSCMP_TEMP" TEMPFILE 'D:\ORADATA\HSCMP\HSCMP_TEMP' SIZE 5G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE SMALLFILE TABLESPACE "HSCMP_COM" DATAFILE 'D:\ORADATA\HSCMP\HSCMP_COM' SIZE 2G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- 建立HSCMP用户

CREATE USER "HSCMP" PROFILE "DEFAULT" IDENTIFIED BY "*******" DEFAULT TABLESPACE "HSCMP_TBL" TEMPORARY TABLESPACE "HSCMP_TEMP" ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "HSCMP" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "HSCMP" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "HSCMP" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "HSCMP" WITH ADMIN OPTION;
GRANT "CONNECT" TO "HSCMP" WITH ADMIN OPTION;
GRANT "DBA" TO "HSCMP" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "HSCMP";

-- 建立readhscmp用户

CREATE USER "READHSCMP" PROFILE "DEFAULT" IDENTIFIED BY "*******" DEFAULT TABLESPACE "HSCMP_TBL" TEMPORARY TABLESPACE "HSCMP_TEMP" ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "READHSCMP" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "READHSCMP" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "READHSCMP" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "READHSCMP" WITH ADMIN OPTION;
GRANT "CONNECT" TO "READHSCMP" WITH ADMIN OPTION;
GRANT "DBA" TO "READHSCMP" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "READHSCMP";

-- 建立readhscmp用户后，需要执行hscmp的存储过程sSys_Create_Synonym来定义同义词（此存储过程需要在导入CMP数据库后执行）。
-- 未导入数据库文件时此过程并不存在。

select * from dba_types where type_oid like 'FD5F%'




