SELECT * FROM tSysLog ORDER BY LogTime DESC;
SELECT * FROM tSysLog WHERE LogPosition LIKE '%ÉÌÆ·°ü%' ORDER BY LogTime DESC;
SELECT * FROM tSysLog WHERE LOGCONTENT LIKE '%1001THYW201405100063%' ORDER BY LogTime DESC;