select * from planb_whitelist
alter table "HSCMP"."PLANB_WHITELIST" add constraint PK_ETPCODE primary key("ETPCODE") 

/*
CREATE TABLE "HSCMP"."PLANB_WHITELIST"
  (
    "ETPCODE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "ETPNAME" VARCHAR2(4000 BYTE),
    "HTCODE"  VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "HTNAME"  VARCHAR2(4000 BYTE),
    CONSTRAINT "PK_ETPCODE" PRIMARY KEY ("ETPCODE", "HTCODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "HSCMP_TBL" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "HSCMP_TBL" ;
*/

