SELECT * FROM tAcpJsJxBody WHERE BillNo = '1001YFJS201204060005'
SELECT BILLNO, YWBILLNO, REMARK, JTAXRATE, WJTOTAL, HJTOTAL FROM TACPJSJXBODY WHERE BILLNO = '1001YFJS201204060005' ORDER BY YWBILLNO

SELECT YWORGNAME, BILLNO, YWBILLNO, REMARK, JTAXRATE, SUM(WJTOTAL) AS WJTOTAL, SUM(HJTOTAL) AS HJTOTAL FROM tAcpJsJxBody WHERE BILLNO = '1001YFJS201204060005' GROUP BY YWORGNAME, BILLNO, YWBILLNO, REMARK, JTAXRATE ORDER BY YWBILLNO

<%--SelectCommand="SELECT BILLNO, YWBILLNO, REMARK, JTAXRATE, WJTOTAL, HJTOTAL FROM TACPJSJXBODY WHERE BILLNO = ? ORDER BY YWBILLNO">--%>
 SelectCommand="SELECT YWORGNAME, BILLNO, YWBILLNO, REMARK, JTAXRATE, SUM(WJTOTAL) AS WJTOTAL, SUM(HJTOTAL) AS HJTOTAL FROM tAcpJsJxBody WHERE (BILLNO = ?)GROUP BY YWORGNAME,BILLNO,YWBILLNO,REMARK,JTAXRATE ORDER BY YWBILLNO">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="BillNoLabel" Name="BILLNO" PropertyName="Text" Type="String" />
                        </SelectParameters>