SELECT 
OTH.BillNo, 
OTH.LrDate, 
OTH.JzDate, 
OTH.CkCode, 
OTH.CkName, 
OTH.ThCount, 
--NVL(WMSL.FREALQTY,0) AS WMSThCount, 
DECODE(WMSR.STAT, '5210','已作废', '6500','完成', '5300','初始', '7000','已使用', '0','未审核') AS WMSStatus,
OTH.SupCode,
OTH.SupName,
OTH.HtCode,
OTH.HtName

FROM 
tOrdThHead OTH, TVENDORRTNREQ@HDWMS WMSR--, TVENDORRTNREQDTL@HDWMS WMSL 

WHERE 
OTH.LrDate BETWEEN '2014-02-01' AND SysDate AND OTH.YwType = '0914' AND OTH.BillNo = WMSR.FSrcNum
ORDER BY BillNo DESC;

SELECT * FROM TVENDORRTNREQ@HDWMS WMSR ORDER BY FSrcNum DESC;

SELECT 
R.FSRCNUM 来源单号,R.NUM 物流单号, DECODE(R.STAT,'5210','已作废','6500','完成','5300','初始','7000','已使用','0','未审核') 状态,
A.FCODE 供应商编码,A.FNAME 供应商名称,E.FCODE 退货货品,E.FNAME 退货名称,NVL(L.FQTY,0)申请数量,NVL(L.FREALQTY,0) 实际退货数量 

FROM TVENDORRTNREQ@HDWMS R,TARTICLE@HDWMS E ,TVENDOR@HDWMS A,TVENDORRTNREQDTL@HDWMS L
WHERE R.NUM=L.NUM AND L.FARTICLE=E.FGID AND R.FVENDOR=A.FGID
ORDER BY R.FSRCNUM;