--SELECT * FROM tSalSale;
SELECT ORGCODE,
  TO_CHAR(XSDATE,'hh24') AS XS_HOUR,
  COUNT(SALENO) AS SALENO_COUNT,
  SUM(SSTOTAL) AS SUM_SSTOTAL
FROM tSalSale
GROUP BY ORGCODE,
  TO_CHAR(XSDATE,'hh24')
ORDER BY ORGCODE,
  TO_CHAR(XSDATE,'hh24');