USE [master] 
GO 
ALTER DATABASE hscscm SET RECOVERY SIMPLE WITH NO_WAIT
GO 
ALTER DATABASE hscscm SET RECOVERY SIMPLE --简单模式 
GO 
USE hscscm
GO 
DBCC SHRINKFILE (N'hscscm_Log' , 11, TRUNCATEONLY)
GO 
USE [master] 
GO 
ALTER DATABASE hscscm SET RECOVERY FULL WITH NO_WAIT
GO 
ALTER DATABASE hscscm SET RECOVERY FULL --还原为完全模式 
GO 